### ISSUE TITLE
Chartist responsiveness not working properly

### ISSUE THREAD

**Issue by nanocatdemen** [niclabs/insight#15]
Sometimes the chartist graphs in the infoview gets too small.

One example of this is when we change the layer with the filter and then we change it back, the chartist graphs become too small

**Comment by madestro** [comment]
¿y qué pasó con esto?

**Comment by nanocatdemen** [comment]
Hay que arreglarlo, refresheando los gráficos de chartist cada vez que se cambie de layer. Lo raro es que pasa solo algunas (pocas) veces.

**Comment by madestro** [comment]
do it
