### ISSUE TITLE
Add custom tabs to dashboard

### ISSUE THREAD

**Issue by dorellang** [niclabs/insight#18]
Currently the dashboard has only two tabs (info and filters). It'd be cool if one could add more custom tabs to it in a clean, for instance add a third config tab that allows you to do further customization for the visualization as shown [here](http://tinypic.com/?t=postupload) without resorting to ugly jquery hacks.

Cheers :D

**Comment by nanocatdemen** [comment]
Can you reupload de image?

**Comment by madestro** [comment]
not valid
